### ISSUE TITLE
Unpin libcxx (or document reason for cap)

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/sagelib-feedstock#161]
https://github.com/conda-forge/sagelib-feedstock/commit/351882a9880577974dbb7c0ab5de5f461100db88 added a cap with no documented reason, neither the [PR](https://github.com/conda-forge/sagelib-feedstock/pull/152) nor the links therein give a clear picture why.

This is preventing the boost migration, because libboost has been built with clang 16 on osx, and thus has a `libcxx >=16` run-requirement that causes a conflict.

**Comment by isuruf** [comment]
It was because of https://github.com/conda-forge/clangdev-feedstock/issues/213

Let's remove that. (It was needed in sagemath's CI as well, and it's removed now, so we are good)
