### ISSUE TITLE
last build takes lots of storage

### ISSUE THREAD

**Issue by isuruf** [conda-forge/sagelib-feedstock#29]
`linux-64/sagelib-8.1-py27_blas_openblas_2.tar.bz2` is 500 MB while `linux-64/sagelib-8.1-py27_blas_openblas_1.tar.bz2` is 150 MB

**Comment by isuruf** [comment]
@saraedum, any idea what might be causing this?

**Comment by saraedum** [comment]
There's a 2GB `info/test/src/build` directory…let's see where this came from.

**Comment by saraedum** [comment]
Oh, I did not know that
```
test:
  source_files:
    # include src/ so we can run Sage's doctests
    - src
```
would actually copy the `src/` directory into the released `bz2`.

**Comment by isuruf** [comment]
Neither did I. Thanks for looking into this.
