### ISSUE TITLE
Error when importing liblinboxsage.so.0

### ISSUE THREAD

**Issue by saraedum** [conda-forge/sagelib-feedstock#30]
sagelib-8.1 fails with:
`
ImportError: /opt/conda/envs/sage/lib/python2.7/site-packages/sage/matrix/../../../../liblinboxsage.so.0: undefined symbol: _ZN6FFPACK7MinPolyIN6Givaro7ModularIddEESt6vectorIdSaIdEEEERT0_RKT_S8_mNS9_16ConstElement_ptrEmNS9_11Element_ptrEmPmNS_18FFPACK_MINPOLY_TAGEmmm
`

The exact details are here: https://gitlab.com/saraedum/conda-sagelib-tests/-/jobs/68311887

**Comment by saraedum** [comment]
So, this was three days ago when it pulled in
```
    linbox-1.4.2               |                0        10.5 MB  conda-forge
    givaro-4.0.4               |                0         2.0 MB  conda-forge
    sagelib:                            8.1-py27_blas_openblas_0      conda-forge [blas_openblas]
```

So, this givaro is not allowed currently (`givaro >=4.0.0,<4.0.3`). And I am also a bit confused about the build number of sagelib. Shouldn't that be `8.1-py27_blas_openblas_3` by now?

**Comment by isuruf** [comment]
conda solver does weird things sometimes. I moved the build numbers 0 and 1 to a separate label. Can you check now?

**Comment by saraedum** [comment]
Ok. I restarted the CI run.

**Comment by saraedum** [comment]
Fixed :)
