### ISSUE TITLE
Inspection with `?` raises an ImportError

### ISSUE THREAD

**Issue by saraedum** [conda-forge/sagelib-feedstock#39]
```
sage: ZZ?
ImportError: No module named conf
```

ArchLinux has the same issue btw.

**Comment by isuruf** [comment]
Is this because we don't build docs?

**Comment by saraedum** [comment]
It could be somehow but `?` does not use the docs but the docstring of the object.

**Comment by saraedum** [comment]
It uses `conf.py` from the docs to resolve some URLs it seems.

**Comment by isuruf** [comment]
See https://github.com/sagemath/sage/blob/854f9764d14236110b8d7f7b35a7d52017e044f8/src/sage/misc/sagedoc.py#L467-L473

**Comment by saraedum** [comment]
That's quite a hack there to resolve some URLs:
```
    oldpath = sys.path
    sys.path = [os.path.join(SAGE_DOC_SRC, 'common')] + oldpath
    from conf import extlinks
    sys.path = oldpath
```
I'll try to fix that upstream as that's also the reason why the docker images are bigger than they would have to be.

**Comment by saraedum** [comment]
This is now https://trac.sagemath.org/ticket/25786.
