### ISSUE TITLE
IPython pinning

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/sagelib-feedstock#46]
The IPython pinning in this recipe doesn't have the `<6` from the sage recipe. This causes the sage doctests to fail on import if you install just `sagelib` because it doesn't work with the newest IPython.  I didn't check if there are other pinning differences between the two recipes. Is there any reason for `sage` to depend on things that `sagelib` already depends on?

**Comment by saraedum** [comment]
I am not perfectly happy with the dependencies currently. The idea was to put on `sage` the dependencies and versions that upstream sage uses. And for `sagelib` to use dependencies that would make `import sage` work.
I am not sure what would be the right approach here. Should we force the dependencies of `sagelib` to be in versions such that everything works (except for things where dependencies are missing completely), i.e., use the same versions on `sagelib` and on `sage`? This would introduce some rather strict pins but probably it makes more sense to ship a working `sagelib` whenever possible even if that leads to conflicts.

**Comment by asmeurer** [comment]
IMO you should put the dependencies as low in the dependency graph as possible, so if `sagelib` has the actual code that depends on ipython, then that's where the dependency should be, and `sage` should just depend on `sagelib` and inherit its dependencies. 

As for the pinning, yeah it sucks. But that's Sage's problem, not ours. We should pin the dependencies as necessary so that the package cannot be broken. RIght now IPython >= 6 breaks sagelib, so the pinning should be on this recipe. 

It's very bad idea to install sage in anything other than a specialized environment specifically for sage. This is not just because of pinning; sage also does some monkeypatching of the standard library when its imported, and some libraries like `mpmath` and its dependents (`sympy`) import it when it can.

**Comment by isuruf** [comment]
Fixed in 8.8.rc1
