### ISSUE TITLE
Check which patches from debian are needed

### ISSUE THREAD

**Issue by isuruf** [conda-forge/sagelib-feedstock#5]
Check which of the patches are needed from debian
Patches already applied upstream or committed in a side branch
Or nearly-finished patches that they'll very probably merge.
- [ ] u0-version-pari-2.9.patch
- [ ] u0-version-singular-4.1.0p2.patch
- [ ] u0-version-pynac-0.7.4.patch
- [ ] u0-fix-libgap-systemwide.patch
- [ ] u0-singular-include-path-for-pynac.patch
- [ ] u0-dont-test-glpk-version.patch
- [ ] u0-fix-preexec-fn.patch
- [ ] u0-use-local-threejs.patch

Patches that have open upstream tickets
- [ ] u1-version-planarity-3.patch
- [ ] u1-version-pbori-boost1.62-hashes.patch
- [ ] u1-version-ecm-7.patch
- [ ] u1-fix-use-lexists-not-exists.patch
- [ ] u1-fix-proper-scipy-rtol.patch
- [ ] u1-fix-dont-require-DISPLAY.patch
- [ ] u1-pip-nowarn.patch
- [ ] u1-fix-atrocious-symlink-logic.patch
- [ ] u1-looser-doctest-basename.patch

Patches that should be upstreamed (may need some work first)
- [ ] u2-version-cddlib-094h.patch
- [ ] u2-reproducible-docs.patch
- [ ] u2-fix-trivial-test-cases.patch
- [ ] u2-fix-less-trivial-test-cases.patch
- [x] u2-fix-sympow-cachedir.patch
- [ ] u2-allow-override-sage-local.patch
- [ ] u2-scripts-dir.patch

Patch Sage to work with dependency Debian packages
These won't change even if Debian and Sage use the same version
Not suitable for upstreaming
- [x] d0-arb.patch
- [ ] d0-cython-sys-path.patch
- [ ] d0-gsl-cblas.patch
- [ ] d0-libgap-sage.patch
- [x] d0-maxima.patch
- [ ] d0-nauty.patch
- [ ] d0-pari.patch
- [ ] d0-pari-stackwarn.patch
- [x] d0-rubiks.patch
- [ ] d0-singular.patch
- [ ] d0-disable-jsmol.patch
- [ ] d0-paths-sharedata.patch
- [ ] d0-paths.patch

Patch Sage to behave as a Debian package
Not suitable for upstreaming
- [ ] d1-install-paths.patch # many things in here could be split into an upstreamable patch
- [ ] d1-sage-cli.patch
- [ ] d1-sage-env.patch
- [ ] d1-fakeroot.patch
- [ ] d1-test-optional.patch
- [ ] d1-multiarch-python-paths.patch
- [ ] d1-doc-docs.patch
- [ ] d1-disable-post-install-tests.patch

Potentially controversial fixes
We had to do these to make things work, at some time in the past
It may be possible to drop these now or in the future; test that first.
- [ ] df-revert-lazy-import-dependent-on-python-patch.patch
- [ ] df-revert-minor-feature-dependent-on-python-patch.patch
- [ ] df-disable-custom-sphinx-logger.patch
- [ ] df-python_security.patch
- [ ] df-sagedoc_avoid_exception.patch
- [ ] df-sage-gap-reset-doctest.patch
- [ ] df-silence_debian_bug_780186.patch
- [ ] df-silence_ecl_opt_signals.patch

Temporary patches for whatever reason
They will eventually be gotten rid of
- [ ] dt-disable-parallel-sphinx.patch
- [ ] dt-version-singular-4-extra-fixes.patch
- [ ] dt-version-glpk-4.60-extra-hacky-fixes.patch
- [ ] dt-r-no-readline.patch
- [ ] dt-more-fix-test-cases.patch
- [ ] dt-work-around-doc-common-conf.patch

**Comment by saraedum** [comment]
What was the purpose of this issue? Do you mean needed as in "doctests fail without"? Or needed as in "does not build without"?
